

GRANT CONNECT ON DATABASE paypay TO paypay;

GRANT USAGE ON SCHEMA public TO paypay;

GRANT SELECT, INSERT, UPDATE,
DELETE ON ALL TABLES IN SCHEMA public TO paypay;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO paypay;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO paypay;

GRANT ALL PRIVILEGES ON DATABASE paypay TO paypay;

ALTER USER  paypay;

ALTER USER paypay WITH SUPERUSER;


CREATE TABLE IF NOT EXISTS "COMPANY_BRANCH_CONTRACT" (
"COMPANY_BRANCH_ID" VARCHAR(255) PRIMARY KEY,
"COMPANY_BRANCH_CONTRACT_ID" VARCHAR(255) PRIMARY KEY,
"COMPANY_BRANCH_CONTRACT_PERSON" VARCHAR(255) PRIMARY KEY,
"COMPANY_BRANCH_CONTRACT_FIRST_NAME" VARCHAR(255) PRIMARY KEY,
"COMPANY_BRANCH_CONTRACT_LAST_NAME" VARCHAR(255) PRIMARY KEY,
"COMPANY_BRANCH_CONTRACT_PHONE_NUMBER" VARCHAR(255) PRIMARY KEY,
"COMPANY_BRANCH_CONTRACT_OFFICE_NUMBER" VARCHAR(255) PRIMARY KEY,
"COMPANY_BRANCH_CONTRACT_FAX_NUMBER" VARCHAR(255) PRIMARY KEY,
"COMPANY_BRANCH_CONTRACT_EMAIL" VARCHAR(255) PRIMARY KEY,
"CREATE_DATE" TIMESTAMP NOT NULL,
"CREATE_BY" VARCHAR(50) NOT NULL,
"UPDATE_DATE" TIMESTAMP,
"UPDATE_BY" VARCHAR(50));
